# Generated by Django 4.1.7 on 2023-03-14 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ingredient", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "difficulty",
                    models.IntegerField(
                        choices=[(1, "Easy"), (2, "Intermediate"), (3, "Hard")],
                        default=1,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="added_recipes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "favourite_by_user",
                    models.ManyToManyField(
                        related_name="fav_recipes", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "ingredients",
                    models.ManyToManyField(
                        related_name="in_recipes", to="ingredient.ingredient"
                    ),
                ),
            ],
        ),
    ]
