# Generated by Django 4.1.7 on 2023-03-15 10:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredient", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="favourite_by_user",
            field=models.ManyToManyField(
                blank=True, related_name="fav_recipes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                blank=True, related_name="in_recipes", to="ingredient.ingredient"
            ),
        ),
    ]
