name: week6_day2

dependencies:
    - python = 3.10.9
    - pip = 23.0.1
    - pip:
          - django == 4.1.7
          - djangorestframework == 3.14.0
          - djangorestframework-simplejwt==5.2.2
