# Generated by Django 4.1.7 on 2023-03-14 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recipe", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cookbook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="added_cookbooks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "favourite_by_user",
                    models.ManyToManyField(
                        related_name="fav_cookbooks", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "recipes",
                    models.ManyToManyField(
                        related_name="in_cookbooks", to="recipe.recipe"
                    ),
                ),
            ],
        ),
    ]
